### ISSUE TITLE
realpath illegal option on macOS 13

### ISSUE THREAD

**Issue by asbjornu** [sp1thas/dropboxignore#57]
**Describe the bug**
All dropboxignore commands seem to invoke Unix commands that possibly behave differently on macOS than on Linux, causing the following error message to be printed to the console repeatedly:

```
usage: realpath [-q] [path ...]
realpath: illegal option -- -
usage: realpath [-q] [path ...]
realpath: illegal option -- -
usage: realpath [-q] [path ...]
realpath: illegal option -- -
usage: realpath [-q] [path ...]
realpath: illegal option -- -
usage: realpath [-q] [path ...]
realpath: illegal option -- -
usage: realpath [-q] [path ...]
realpath: illegal option -- -
```

**To Reproduce**
1. Install dropboxignore on macOS 13.5.2.
2. Execute any dropboxignore command.
3. Notice how `usage: realpath [-q] [path ...]` is printed to the console.

**Expected behavior**
I expect the command to work.

**Desktop (please complete the following information):**
 - OS: macOS 13.5.2
 - Version: 1.2.2

**Comment by asbjornu** [comment]
It seems like `shell-testing.yml` is only run on `ubuntu-22.04`.

https://github.com/sp1thas/dropboxignore/blob/9fc7426def920d45bac098002feac5a6458fe31b/.github/workflows/shell-testing.yml#L31

Perhaps it would be good to also run it on `macos-latest`, like `python-testing.yml` is?

https://github.com/sp1thas/dropboxignore/blob/9fc7426def920d45bac098002feac5a6458fe31b/.github/workflows/python-testing.yml#L31

**Comment by asbjornu** [comment]
As #59 did not actually run the unit tests, I'm not sure how to move forward with this. It would be nice to see a failing build first and then fix it afterward, turning the build green. Can you please assist @sp1thas?

**Comment by sp1thas** [comment]
Good point @asbjornu the workflow didn't run because I had to make [this](https://github.com/sp1thas/dropboxignore/commit/a48b5af5facb621cd8de64912d19701a0389b637) change first, as you can see [here](https://github.com/sp1thas/dropboxignore/actions/runs/6261427791/job/17790289931), the unittests (`Run bats tests` pipeline step) executed successfully, therefore, I guess this issue occurs only in macOS >= 13.x

I will try to test it using the `macos-13` runner 🙏🏿
